#
# Generate form
#
-
  name: 'Generate nodetype'
  uriPattern: ''
  httpMethods: ['GET']
  defaults:
    '@controller': 'NodeGenerator'
    '@action': 'generateForm'
  appendExceedingArguments: TRUE
